[package]
name = "space-game"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
ggez = "0.4"
alga = "0.5"
nalgebra = "0.13"
slog = "2"
sloggers = "0.2"
metrohash = "1.0.5"
pathfinding = "0.6.8"

# Debug mode performance without any optimizations is way too slow for games
[profile.dev]
opt-level = 1
