[workspace]
members = [
    "voxelgame/voxelgame-client",
    "voxelgame/voxelgame-server",
    "mtk/mtk",
    "rivr/rivr",
    "rivr/rivr-ggez",
    "spacegame",
    "spacegame-game",
]

# Debug mode performance without any optimizations is way too slow for games
[profile.dev]
opt-level = 1
