[workspace]
members = [
    "markedly/markedly",
    "markedly/markedly-ggez",
    "space-game",
]

# Debug mode performance without any optimizations is way too slow for games
[profile.dev]
opt-level = 1
